spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chronova_db
    username: postgres
    password: 99016887
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SUPPORT_EMAIL}
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret:  ${JWT_SECRET_KEY:defaultSecretKeyIfNotSet}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds
